import type { Product } from '../types'

export const mockProducts: Product[] = [
  {
    id: 'p001',
    name: '春季新款法式碎花连衣裙',
    price: 129,
    originalPrice: 299,
    imageUrl: '/mock-products/dress-01.jpg',
    category: 'clothing',
    attributes: {
      material: '雪纺',
      sizes: ['S', 'M', 'L', 'XL'],
      colors: ['米白底蓝花', '粉色碎花', '藏青底白花'],
      fit: '收腰A字版型',
    },
    salesCount: 2341,
    rating: 4.8,
    description: '2025春季新款法式碎花连衣裙，轻盈雪纺面料，透气舒适。收腰设计显瘦，适合日常通勤、约会出游。',
    hostComment: '这个面料超舒服的！我160cm穿S码刚刚好，喜欢的宝宝赶紧拍！',
    tags: ['春季新款', '显瘦', '通勤', '约会'],
  },
  {
    id: 'p002',
    name: '玻尿酸补水保湿面膜 10片装',
    price: 49.9,
    originalPrice: 99,
    imageUrl: '/mock-products/mask-01.jpg',
    category: 'skincare',
    attributes: {
      material: '蚕丝膜布',
      skinType: ['干性', '中性', '混合性'],
      effect: '深层补水、锁水保湿',
      ingredients: '玻尿酸、神经酰胺、甘油',
      shelfLife: '3年',
    },
    salesCount: 15234,
    rating: 4.9,
    description: '三重玻尿酸精华，采用进口蚕丝膜布，贴合面部。无酒精无香精，敏感肌可用。一盒10片，建议每周2-3次。',
    hostComment: '我自己用了三盒了！敷完第二天皮肤水嫩嫩的，上妆特别服帖！',
    tags: ['补水', '敏感肌可用', '爆款', '囤货'],
  },
  {
    id: 'p003',
    name: '复古牛皮手工小方包',
    price: 358,
    originalPrice: 699,
    imageUrl: '/mock-products/bag-01.jpg',
    category: 'accessories',
    attributes: {
      material: '头层牛皮',
      colors: ['棕色', '黑色', '酒红'],
      weight: '约450g',
      sizes: ['均码（22×16×8cm）'],
    },
    salesCount: 892,
    rating: 4.7,
    description: '意大利进口头层牛皮，纯手工缝制。复古做旧五金件，可单肩可斜挎，容量刚好放下手机和日常小物。',
    hostComment: '这个皮质真的绝了！越用越有味道，送人自用都很有面子！',
    tags: ['真皮', '手工', '复古', '送礼'],
  },
  {
    id: 'p004',
    name: '美白淡斑精华液 30ml',
    price: 189,
    originalPrice: 359,
    imageUrl: '/mock-products/serum-01.jpg',
    category: 'skincare',
    attributes: {
      material: '滴管瓶装',
      skinType: ['所有肤质'],
      effect: '美白淡斑、提亮肤色',
      ingredients: '烟酰胺、维C衍生物、熊果苷',
      shelfLife: '2年',
    },
    salesCount: 6721,
    rating: 4.6,
    description: '高浓度烟酰胺+VC复合配方，28天改善暗沉。通过国家药监局美白特证，温和不刺激，建议晚间使用。',
    hostComment: '想要白的姐妹一定要试试！我自己用了两周就能看到效果！',
    tags: ['美白', '淡斑', '持证', '热卖'],
  },
  {
    id: 'p005',
    name: '网红同款透气飞织运动鞋',
    price: 199,
    originalPrice: 459,
    imageUrl: '/mock-products/sneaker-01.jpg',
    category: 'clothing',
    attributes: {
      material: '飞织网面+EVA大底',
      sizes: ['36', '37', '38', '39', '40', '41', '42', '43'],
      colors: ['白灰', '黑色', '粉白', '薄荷绿'],
      fit: '标准码，建议按正常尺码选',
    },
    salesCount: 4521,
    rating: 4.5,
    description: '3D飞织一体鞋面，透气不闷脚。EVA轻量缓震大底，单只仅重180g。适合跑步、健身、日常穿搭。',
    hostComment: '上脚超轻！走路像踩在云朵上，我每天直播穿它站5小时都不累！',
    tags: ['轻量', '透气', '百搭', '运动'],
  },
  {
    id: 'p006',
    name: '新疆和田大枣 500g×2袋',
    price: 39.9,
    originalPrice: 79.9,
    imageUrl: '/mock-products/jujube-01.jpg',
    category: 'food',
    attributes: {
      origin: '新疆和田',
      weight: '500g×2袋',
      shelfLife: '12个月',
      material: '特级大枣',
    },
    salesCount: 32156,
    rating: 4.9,
    description: '新疆和田直供，颗颗精选。自然吊干，肉厚核小，甜度高。即食、泡茶、煲汤均可。',
    hostComment: '我姥姥特别爱吃这个枣！正宗新疆和田枣，颗颗饱满，煮粥放两颗超甜的！',
    tags: ['新疆特产', '特级', '复购王', '健康零食'],
  },
  {
    id: 'p007',
    name: '简约纯棉宽松T恤 多色可选',
    price: 69,
    originalPrice: 149,
    imageUrl: '/mock-products/tshirt-01.jpg',
    category: 'clothing',
    attributes: {
      material: '100%新疆长绒棉',
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['白色', '黑色', '灰色', '雾霾蓝', '牛油果绿'],
      fit: '宽松落肩版型',
    },
    salesCount: 8972,
    rating: 4.7,
    description: '260g重磅纯棉，不透不塌。二本针领口加固，机洗不变形。落肩设计不挑身材，男女同款。',
    hostComment: '这件我自留了三个颜色！重磅棉质感就是不一样，绝对不会透！',
    tags: ['纯棉', '重磅', '基础款', '男女同款'],
  },
  {
    id: 'p008',
    name: '智能蓝牙降噪耳机 Pro版',
    price: 299,
    originalPrice: 599,
    imageUrl: '/mock-products/earphone-01.jpg',
    category: 'electronics',
    attributes: {
      material: 'ABS+金属',
      weight: '充电盒约45g',
      effect: 'ANC主动降噪',
      colors: ['白色', '黑色', '蓝色'],
    },
    salesCount: 3412,
    rating: 4.4,
    description: '混合主动降噪，深度可达40dB。蓝牙5.3低延迟，支持游戏模式。总续航28小时，支持无线充电。',
    hostComment: '这个降噪效果真的惊艳！地铁上戴完全听不到噪音，性价比炸裂！',
    tags: ['降噪', '长续航', '游戏模式', '性价比'],
  },
]